services:
  express:
    build:
      context: ./server
      dockerfile: express.Dockerfile
    container_name: cosmosound_backend
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      traefik:
        condition: service_completed_successfully
      mongodb-setup:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cosmosound_internal.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.cosmosound_internal.entrypoints=web"
      - "traefik.http.services.cosmosound_internal.loadbalancer.server.port=4000"
    restart: unless-stopped
    networks:
      - cosmosound_internal


  mongodb:
    container_name: cosmosound_database
    build: 
      context: ./server/mongodb_rs/
      dockerfile: mongodb.Dockerfile
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok | mongosh localhost:27017/test --quiet'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
     - cosmosound_internal


  mongodb-setup:
    image: mongo:8.0
    container_name: mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --username root --password root --host mongodb --port 27017 --eval '
        config = {
          "_id": "rs0",
          "members": [
            { "_id": 0, "host": "mongodb:27017", "priority": 1 }
          ]
        },
        rs.initiate(config);'
    networks:
     - cosmosound_internal


  react_front:
    build:
      context: ./client
      dockerfile: react.Dockerfile
    container_name: cosmosound_frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - web


networks:
  web:
    external: false
  cosmosound_internal:
    external: false

volumes:
  mongodb_data:
    driver: local
  node_modules: