services:
  express:
    image: registry.luhcaran.fr/cosmosound_backend:v0.2
    container_name: cosmosound_backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.cosmosound_api.rule=Host(`api.cosmosound.luhcaran.fr`)
      - traefik.http.routers.cosmosound_api.entrypoints=websecure
      - traefik.http.routers.cosmosound_api.tls=true
      - traefik.http.routers.cosmosound_api.tls.certresolver=letsencryptresolver
      - traefik.http.services.cosmosound_api.loadbalancer.server.port=4000
    networks:
      - web
      - cosmosound_internal
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  react_front:
    image: registry.luhcaran.fr/cosmosound_frontend:v0.2
    container_name: cosmosound_frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.cosmosound_frontend.rule=Host(`cosmosound.luhcaran.fr`)
      - traefik.http.routers.cosmosound_frontend.entrypoints=websecure
      - traefik.http.routers.cosmosound_frontend.tls.certresolver=letsencryptresolver
      - traefik.http.services.cosmosound_frontend.loadbalancer.server.port=80
    networks:
      - web
      - cosmosound_internal
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    container_name: cosmosound_database
    image: registry.luhcaran.fr/cosmosound_database:v0
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - cosmosound_internal

  mongodb-setup:
    image: mongo:6.0
    container_name: mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --username root --password root --host mongodb --port 27017 --eval '
        config = {
          "_id": "rs0",
          "members": [
            { "_id": 0, "host": "mongodb:27017", "priority": 1 }
          ]
        },
        rs.initiate(config);'
    networks:
      - cosmosound_internal

networks:
  web:
    external: true
  cosmosound_internal:
    driver: bridge

volumes:
  mongodb_data:
    driver: local