services:
  express:
    build:
      context: ./server
      dockerfile: express.Dockerfile
    container_name: cosmosound_backend
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.cosmosound_internal.rule=Host(`backend.localhost`)
      - traefik.http.routers.cosmosound_internal.entrypoints=web
      - traefik.http.services.cosmosound_internal.loadbalancer.server.port=4000
    restart: unless-stopped
    networks:
      - cosmosound_local
      - web

  traefik:
    image: traefik:v3.2
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - cosmosound_local
      - web

  mongodb:
    container_name: cosmosound_database
    build: 
      context: ./server/mongodb_rs/
      dockerfile: mongodb.Dockerfile
    ports:
      - "27017:27017" # Exposes MongoDB locally
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - cosmosound_local

  mongodb-setup:
    image: mongo:6.0 # Updated version
    container_name: mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --username root --password root --host mongodb --port 27017 --eval '
        config = {
          "_id": "rs0",
          "members": [
            { "_id": 0, "host": "mongodb:27017", "priority": 1 }
          ]
        },
        rs.initiate(config);'
    networks:
      - cosmosound_local

  react_front:
    build:
      context: ./client
      dockerfile: react.Dockerfile
    container_name: cosmosound_frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.cosmosound_frontend.rule=Host(`frontend.localhost`)
      - traefik.http.services.cosmosound_frontend.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - cosmosound_local
      - web

networks:
  web:
  cosmosound_local:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  node_modules: