services:
  express:
    build:
      context: ./server
      dockerfile: express.Dockerfile
    container_name: cosmosound_backend
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.cosmosound_internal.rule=Host(`api.cosmosound.chaboisseau.net`)
      - traefik.http.routers.cosmosound_internal.entrypoints=web
      - traefik.http.services.cosmosound_internal.loadbalancer.server.port=4000
    restart: unless-stopped
    networks:
      - cosmosound_internal
      - web

  mongodb:
    container_name: cosmosound_database
    build: 
      context: ./server/mongodb_rs/
      dockerfile: mongodb.Dockerfile
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - cosmosound_internal


  mongodb-setup:
    image: mongo:6.0 # Updated version
    container_name: mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --username root --password root --host mongodb --port 27017 --eval '
        config = {
          "_id": "rs0",
          "members": [
            { "_id": 0, "host": "mongodb:27017", "priority": 1 }
          ]
        },
        rs.initiate(config);'
    networks:
      - cosmosound_internal


  react_front:
    build:
      context: ./client
      dockerfile: react.Dockerfile
    container_name: cosmosound_frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`cosmosound.chaboisseau.net`)
      - traefik.http.services.web.loadbalancer.server.port=80
    networks:
      - web
      - cosmosound_internal


networks:
  web:
  cosmosound_internal:
    external: false

volumes:
  mongodb_data:
    driver: local
  node_modules: