services:
  express:
    image: reg.chaboisseau.net/cosmosound_backend:v0
    container_name: cosmosound_backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.cosmosound_internal.rule=Host(`cosmosound.chaboisseau.net`)
      - traefik.http.routers.cosmosound_internal.entrypoints=web
      - traefik.http.services.cosmosound_internal.loadbalancer.server.port=4000
    restart: unless-stopped
    networks:
      - cosmosound_internal
      - web


  mongodb:
    container_name: cosmosound_database
    image: reg.chaboisseau.net/cosmosound_database:v0
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - cosmosound_internal

  mongodb-setup:
    image: mongo:6.0
    container_name: mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --username root --password root --host mongodb --port 27017 --eval '
        config = {
          "_id": "rs0",
          "members": [
            { "_id": 0, "host": "mongodb:27017", "priority": 1 }
          ]
        },
        rs.initiate(config);'
    networks:
      - cosmosound_internal

  react_front:
    image: reg.chaboisseau.net/cosmosound_frontend:v0
    container_name: cosmosound_frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.cosmosound_frontend.rule=Host(`cosmosound.chaboisseau.net`)
      - traefik.http.services.cosmosound_frontend.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - cosmosound_internal
      - web

networks:
  web:
  cosmosound_internal:
    driver: bridge

volumes:
  mongodb_data:
    driver: local