name: CI/CD

on:
  push:
    branches: [main, 'temp/*']

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_IMAGE_NAME: cosmosound_database
      FRONTEND_IMAGE_NAME: cosmosound_frontend
      BACKEND_IMAGE_NAME: cosmosound_backend
      REGISTRY: ${{ secrets.REGISTRY_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set app version
        run: echo "appVersion=${{ github.run_number }}-${{ github.sha }}" >> $GITHUB_ENV

      - name: Log into Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Database Docker image
        run: |
          cd server/mongodb_rs
          docker build -t ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:${{ env.appVersion }} .
          docker push ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:${{ env.appVersion }}

      - name: Build and push Frontend Docker image
        run: |
          cd client
          docker build -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.appVersion }} .
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.appVersion }}

      - name: Build and push Backend Docker image
        run: |
          cd server
          docker build -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.appVersion }} .
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.appVersion }}

      - name: Trigger Portainer webhook
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}